site_name: Epiverse Readthedocs
repo_url: https://github.com/DBinary/Epiverse
site_author: "Lei Hu&Zehua Zeng"
copyright: "Copyright &copy; 2022-2023, 112 Lab, USTB"


nav:
- Index: index.md
- Installation: Installation_guild.md
- Tutorial:
    - Bulk:
        - ATAC-seq visualization: Tutorials-bulk/t_bulk_visualize.ipynb
    - Single:
        - Preprocessing the data of scATAC-seq: Tutorials-single/t_preprocess.ipynb
        - Data integration: Tutorials-single/t_single_concat.ipynb
        - Calculating the gene activity matrix of scATAC-seq: Tutorials-single/t_gene_activity.ipynb


- API documentation: api/index.md
- Release notes: Release_notes.md
- Developer guild: Developer_guild.md

  


plugins:
  - mkdocs-jupyter
  - glightbox
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/ico.png
  favicon: img/favicon.ico

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - css/custom.css